---
title: "25-08"
output: html_document
date: "2022-08-25"
---
Ejercicio 1 
Cargamos el archivo
Analogo para los demas breacks
```{r}
buffalo = scan("buffalo.txt")
hist(buffalo, col="brown",breaks = seq(20,130,10), probability = TRUE)
```
Ejercicio 2:
```{r}
library("ggplot2")
x = 10
hist(buffalo, col ="brown", breaks = seq(x,130,10), probability = TRUE)
```


Ejercicio 3:
```{r}
f = function(D,x,h){
  n = length(D)
  res = 0
  for (v in D) {
    if( x - h <= v && v  <= x + h ) res = res + 1 
  }
  return(res/n)
}
```

Ejercicio 4:
modificamos la funcion para que esta bien definida para que tome vectores como parametros en x = vector 
```{r}
f2 = function(D,X,h){
  n = length(D)
  for (v in D) {
    res = 0
    for(x in X){
      if( x - h <= v && v  <= x + h ) res = res + 1   
    }
    
  }
  
  return(res/n)
}

for (x in buffalo) {
  f(buffalo,x,30)
    est.append
  }

```

```{r}
library("ggplot2")
sexo = datos$Sexo
ggplot(datos, aes(Peso)) + geom_boxplot(aes(group =  sexo, fill = sexo, alpha=0.35))
```




