---
title: "clase-practica-18-08"
output: pdf_document
date: "2022-08-19"
---

Ejericios de Clase:
a)
```{r}
res <- 0
for( i in 1:141){
  res <- res + i 
}
print(res) 
```

b)
```{r}
res <- 1
i <- 1
valor = i
while(valor <= 10000){
  i = i + 1 
  valor = valor + i 
  res = res + 1
}
print(res)
```

c)
```{r}
suma = function(v){
  res = 0
  for(i in 1:length(v) ){
    res = res + v[i]   
  }
  return(res) 
}
print(res)
```

Ejercicio 2 
```{r}
f = function(x){
  return(x*(1-x))
}

v = seq(0,1,0.2)
plot(v,f(v))
```

Ejercicio 3 
```{r}
x = -50:50 
plot(x,sin(x), main='graficos de funciones',type="l",col="red",lwd=3,xlab="",ylab="")
lines(x,cos(x**2), col="blue")
lines(x,cos(x), col="green",lwd=3)
legend("bottomleft",col=c("red","blue","green"),legend = c("sen","cos","cos(x**2)"),lwd=3)
```
Para seleccionar el directorio donde vamos a trabajar vamos a: 
session -> set work directory ... 
luego dependiendo del data-set se usar diferentes tipos de funcines 

```{r}
autos = read.table("autos.txt")
```
